### PR TITLE
fix: on windows paths are not correctly escaped

### LINKED ISSUE #1: On Windows path separator (\) needs to be escaped (\\) or better replaced with forward slash
See sample repo https://github.com/manwithafox/esbuild-dirname-issue-on-windows/tree/main
```
C:\dev\esbuild-dirname-issue-on-windows (master)>npm run package

> esbuild-dirname-issue-on-windows@1.0.0 package
> node build

X [ERROR] Syntax error "t"

    src/util/index.ts:3:111:
      3 │           filename: "C:\dev\esbuild-dirname-issue-on-windows\src\util\index.ts",
        ╵                                                                   ^

C:\dev\esbuild-dirname-issue-on-windows (master)>
```
Sample only fails because the path contains a `util` folder which then gets rendered as **\u**til without 4-digit unicode following. Else it would live on undiscovered.
Backslash path separator needs to be escaped or better replaced by forward slash, matching the relative path.
Expected output of sample repo would be:

```
// src/util/index.ts
var __fileloc = {
  filename: "C:/dev/esbuild-dirname-issue-on-windows/src/util/index.ts",
  dirname: "C:/dev/esbuild-dirname-issue-on-windows/src/util",
  relativefilename: "src/util/index.ts",
  relativedirname: "src/util"
};
var utilFilename = __fileloc.filename;

// src/index.ts
console.log(utilFilename);
```

### PR DESCRIPTION
**Pull request by manwithafox**
fixes #1

Change-Id: Ie7fb394a94ab20b389e680cf4ef5b7acf1fe4ed5

### CODE REVIEW

**Comment by martonlederer** [comment]
Please ping me if i forget to release this

**Comment by manwithafox** [comment]
No update on [npmjs.org](https://www.npmjs.com/package/esbuild-plugin-fileloc) yet. Please release.

Thanks <3

**Comment by martonlederer** [comment]
I'm not home yet, I meant like in a day or two

**Comment by manwithafox** [comment]
Ah, I see. Sorry. Will check tomorrow, thanks

**Pull request merged**
